levels:
  "3":
    down:
      temp: 85
      target: 1

  "1":
    up:
      temp: 90
      target: 3
    down:
      temp: 80
      target: 2

  "2":
    up:
      temp: 85
      target: 1
    down:
      temp: 70
      target: 0

  "0":
    up:
      temp: 75
      target: 2
    down:
      temp: 50
      target: 255

  "255":
    up:
      temp: 55
      target: 0